### ISSUE TITLE
Save all for bulk edit

### ISSUE THREAD

**Issue by caiwan** [slapec/wimm#15]
When you bulk edit multiple entries, that would be neat if a save button could save every item you've edited rather than click on every single save button next to the item, like the undo works. In addition the delete button could be replaced, however it is disabled anyway when you are in edit mode.

**Comment by slapec** [comment]
See https://github.com/slapec/wimm-vue/issues/5

**Comment by caiwan** [comment]
What happened with this particular issue then? Have it been implemented, or was it tossed away?

**Comment by slapec** [comment]
It's a client side thing so: https://github.com/slapec/wimm-vue/issues/5
