### ISSUE TITLE
Listing per date gets messed up after edit

### ISSUE THREAD

**Issue by caiwan** [slapec/wimm#16]
**Bug:** After editing an item, the date listing gets at the end of the list when save. After refresh it listed correctly.
**Expected behavior:** When editing an item with date, the date gets parsed and listed correctly.
**Steps to reproduce:**
- have items to edit
- open edit mode
- edit their date - add or miss  trailing zeroes on purpose to break the format like *14-15-9* or *000-4-20*
- save them
- the edited items are listed separately - at the bottom - after save

**Comment by slapec** [comment]
See https://github.com/slapec/wimm-vue/issues/4
