### ISSUE TITLE
Editing an income becomes an expense after save

### ISSUE THREAD

**Issue by caiwan** [slapec/wimm#17]
**Bug:** After editing and saving an item, which is an income (*positive value*) becomes an expense (*negative value*) because of negative default value on editing, and forgets the plus sign.
**Expected behavior:** After saving an item with positive value, it stays as an income, unless you remove the plus sign.
**Steps to reproduce:**
- have an income item
- edit it
- save it
- observe it

**Comment by slapec** [comment]
To tell you the truth I am fine with this behaviour. It might be confusing that as you toggle to edit mode minus and plus signs swap. I should drop showing minus signs and leave plus only so the data and the input would become consistent.

**Comment by slapec** [comment]
See https://github.com/slapec/wimm-vue/issues/7
